"""
Test that the workflow inputs generated by the Cromwell job runner and the WDLs
specified in the workflow configuration are valid and can be submitted to a job runner.

Test that the input file can take a URL from https://data.microbiomedata.org/data/ and
map it to /global/cfs/cdirs/m3408/results/.
"""
import json
import logging
import os
import pytest
import zipfile

from nmdc_automation.workflow_automation.wfutils import WorkflowStateManager

logging_level = os.getenv("NMDC_LOG_LEVEL", logging.INFO)
logging.basicConfig(
    level=logging_level, format="%(asctime)s %(levelname)s: %(message)s"
)

logger = logging.getLogger(__name__)

@pytest.mark.integration
@pytest.mark.parametrize(
    "fixture", ["rqc_workflow_state.json",
                "meta_assembly_workflow_state.json",
                "read_based_analysis_workflow_state.json",
                "mags_workflow_state.json",
                "annotation_workflow_state.json",
                "metat_rqc_workflow_state.json",
                "metat_assembly_workflow_state.json",
                "metat_annotation_workflow_state.json",
                "metat_expression_workflow_state.json"
                ]
    )
def test_workflow_inputs_and_wdl(site_config, fixtures_dir, fixture):
    """
    Test that the workflow submission files generated by the WorkflowStateManager are valid
    compared to the WDLs specified in the workflow configuration yaml file.

    This test requires that WOMtool be installed and available in the PATH.
    https://cromwell.readthedocs.io/en/stable/WOMtool/
    """


    job_state = json.load(open(fixtures_dir / fixture))
    state_manager = WorkflowStateManager(job_state)

    submission_files = state_manager.generate_submission_files(for_jaws=True)

    # For now, we have to manually unzip the sub workflow zip file
    if submission_files.get("sub"):
        extract_dir = os.path.dirname(submission_files["sub"])
        with zipfile.ZipFile(submission_files["sub"], 'r') as zip_ref:
            zip_ref.extractall(extract_dir)

    # Validate the WDLs and inputs using the WOMtool CLI womtool validate command
    wdl_file = submission_files["wdl_file"]
    inputs = submission_files["inputs"]

    # Validate the WDL
    wdl_validate_cmd = f"womtool validate {wdl_file} --inputs {inputs}"
    logger.info(f"Validating WDL: {wdl_file}")
    logger.info(f"Command: {wdl_validate_cmd}")
    os.system(wdl_validate_cmd)

def test_workflow_inputs_url_to_path(site_config, fixtures_dir):
    """
    Test that when given an input file with a URL from https://data.microbiomedata.org/data/,
    it will be replaced with the path to /global/cfs/cdirs/m3408/results/

    """
    # input types
    input_types = ("file", "files", "fq1", "fq2", "fastq1", "fastq2")

    # Using the mags_workflow_state.json to test inputs
    job_state = json.load(open(fixtures_dir / "manifest_workflow_state_2.json"))
    workflow = WorkflowStateManager(state = job_state, site_config = site_config)

    # Function to replace URL with file path
    inputs = workflow.generate_workflow_inputs()
    assert inputs

    original_inputs = job_state["config"]["inputs"]

    # The values are in a key-value dict with file paths as values
    for key, value in inputs.items():
        # Only test file inputs
        if not key.endswith(input_types):
            continue

        original_key = key.replace(f"{workflow.input_prefix}.", "")
        original_value = original_inputs.get(original_key)


        if isinstance(original_value, list):
            for orig, mapped in zip(original_value, value):
                if orig.startswith("https://data.microbiomedata.org/data/"):
                    logger.info(f"original value: {orig}")
                    logger.info(f"mapped value: {value}")
                    assert not mapped.startswith("https")
                    assert mapped.startswith("/global/cfs/cdirs/m3408/results/")
                else:
                    logger.info(f"original value: {original_value}")
                    logger.info(f"mapped value: {value}")
                    assert mapped == orig
        else:
            if original_value.startswith("https://data.microbiomedata.org/data/"):
                logger.info(f"original value: {original_value}")
                logger.info(f"mapped value: {value}")
                assert not value.startswith("https")
                assert value.startswith("/global/cfs/cdirs/m3408/results/")
            else:
                logger.info(f"original value: {original_value}")
                logger.info(f"mapped value: {value}")
                assert value == original_value
