name: Build and push img-omics container image to GHCR

# Run this workflow whenever a Dockerfile is updated.
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - '**'
        paths:
            - 'Dockerfile'

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
            - name: Authenticate with container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
              # Use the `docker/build-push-action` action to build the image described
              # by the specified Dockerfile. If the build succeeds, push the image to GHCR.
              # This action uses the `tags` parameters to tag the image with the Git tag name
              # the image, respectively, with the output from the "get_version" step above.
              # For more info: https://github.com/docker/build-push-action#usage.
            - name: Build and push container image
              id: push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ghcr.io/microbiomedata/sched:$(date +'%Y%m%d')

            # - name: Build the Docker image
            #   run: docker build . --file Dockerfile --tag microbiomedata/sched:$(date +'%Y%m%d')

# References:
# - https://docs.github.com/en/actions/learn-github-actions/variables#using-the-vars-context-to-access-configuration-variable-values
# - https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
# - https://github.com/microbiomedata/nmdc-edge/blob/main/.github/workflows/build-and-push-image.yml
# - https://stackoverflow.com/questions/59191913/how-do-i-get-the-output-of-a-specific-step-in-github-actions